/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "The only board the AIs might be good": "唯一的棋盘 AI 可能是好的",
    "Upgrade Ais": "升级 Ai",
    "Upgrade All Ai Skills": "升级所有 AI 技能",
    "Upgrade All Ai Speeds": "升级所有 Ai 速度",
    "Upgrade All Board Skill": "升级所有棋盘技能",
    "Upgrade All Board Skills": "升级所有棋盘技能",
    "Upgrade All Board Speeds": "升级所有棋盘速度",
    "Upgrade Skill": "升级技能",
    "Upgrade Speed": "升级速度",
    "Upgrade Speed +5%": "升级速度 +5%",
    "Upgrade Tier": "升级层",
    "Skill": "技能",
    "Skill:": "技能:",
    "Speed": "速度",
    "Standard run of the mill ticcoin miner": "Mill ticcoin 矿工的标准运行",
    "This game is pretty kinky so you can collect Toes which you can use as a currency in the Toe Shop to unlock bonuses and upgrades. You can also upgrade your Tier to unlock more. Earn Tics to get a spot on the leader board and battle to be the biggest Nerd, good luck losers.": "这个游戏非常古怪，所以你可以收集Toes，你可以在Toes商店中用作货币来解锁奖金和升级。 您还可以升级您的等级以解锁更多。 赚取 Tics 以在排行榜上占据一席之地，并争取成为最大的书呆子，祝你好运失败者。",
    "To progress, buy more boards. There are three types of boards with different advantages. We know you are a selfish bastard so you can buy as many boards as you like. Upgrades are listed on the board and to delete a board use the button in the top right. To beat the game delete the first board.": "要进步，请购买更多棋盘。 三种类型的棋盘具有不同的优点。 我们知道您是一个自私的混蛋，因此您可以购买任意数量的棋盘。 升级列在棋盘上，要删除棋盘，请使用右上角的按钮。 要击败游戏，请删除第一个棋盘。",
    "Welcome to Idle Noughts, the worlds first Idle TicTacToe game. In Idle Noughts you play TicTacToe to get money called ‘Tics’, use Tics to buy AI, use Ai to play more, play more to get more Tics, use more Tics to get more upgrades. Every time you lose or tie you get a tac, save Tacs for later.": "欢迎来到 Idle Noughts，这是世界上第一个 Idle TicTacToe 游戏。 在 Idle Noughts 中，您玩 TicTacToe 以获得称为“Tics”的钱，使用 Tics 购买 AI，使用 Ai 玩更多游戏，玩更多游戏以获得更多 Tics，使用更多 Tics 获得更多升级。 每次您输掉或打平时，您都会得到一个 tac，保存 Tacs 以备后用。",
    "New Game Plus": "新游戏+",
    "Not the brightest AI out there. Takes after it's namesake.": "不是最聪明的 AI。 以它的名字命名。",
    "Numerical Board": "数位板",
    "Recycle": "回收",
    "Restart": "重新开始",
    "Toe Converter AI": "Toes转换器 AI",
    "Toe Shop": "Toes商店",
    ">Click here for a free 500 Bitcoin (NO JOKE)<": ">单击此处免费获得 500 比特币（不开玩笑）<",
    "Adult AI": "成人AI",
    "An Irish teen-pop board": "爱尔兰青少年流行乐",
    "Delete Board": "删除棋盘",
    "Digital enbodiement of the devolper.": "开发人员的数字化体现。",
    "Every time you lose a game you get a Tac, nobody wants Tacs because it means you suck dick, especially if you are using Jai bots. Luckily for your ungrateful ass you can buy Converter AIs which convert Tacs into something useful such as Tics or Toes.": "每次你输掉一场比赛你都会得到一个 Tac，没有人想要 Tacs，因为这意味着你很烂，尤其是当你使用 Jai 机器人时。 幸运的是，对于您忘恩负义的屁股，您可以购买转换器 AI，它将 Tacs 转换为有用的东西，例如 Tics 或 Toes。",
    "Gain": "获得",
    "Genius AI": "天才AI",
    "In Idle Noughts you can buy AIs to do your work, you lazy fuck. There are different AI’s who act differently. You start with a Jai bot. Each bot has increasing intelligence, except Jai bot who doesn’t have a brain because he is retarted. In the tool bar you can upgrade your bots to play faster and learn faster. Learning faster means they will win more games. If your bot isn’t satisfactory you can recycle it for spare Tics, I recommend recycling Jai bot because it is a needy whore.": "在 Idle Noughts 中，你可以购买 AI 来完成你的工作，你这个懒鬼。 有不同的人工智能有不同的行为。 你从一个 Jai 机器人开始。 每个 bot 的智能都在增加，除了 Jai bot 因为他被拒绝而没有大脑。 在工具栏中，您可以升级您的机器人以更快地玩和更快地学习。 学得更快意味着他们将赢得更多比赛。 如果您的机器人不满意，您可以将其回收为备用 Tics，我建议回收 Jai 机器人，因为它是一个有需要的鸡。",
    "Mid AI": "中型AI",
    "Downgrade Skill -5%": "降级技能-5%",
    "Board Ais ⬆︎": "棋盘AI ⬆︎",
    "Boards": "棋盘",
    "BUY MONEY $$$": "买钱 $$$",
    "Change Username: gityx": "更改用户名：gityx",
    "Close": "关",
    "Converter Ais ⬆︎": "转换器 Ais ⬆︎",
    "DM me if you have joke": "有笑话就私信我",
    "Gold Basic Board": "黄金基础板",
    "Gold Board": "金板",
    "How To Play": "怎么玩",
    "I would make a baby related joke but I've never had a baby before. Still better than Jai AI tho": "我会开一个与婴儿有关的笑话，但我以前从未生过孩子。 还是比Jai AI tho好",
    "IDK I don't listen to their music": "IDK 我不听他们的音乐",
    "Idle Noughts": "Idle Noughts",
    "Infinite Toes": "无限脚趾",
    "Introduction": "介绍",
    "Leaderboard": "排行榜",
    "- Type": "- 类型",
    "Baby AI": "宝宝AI",
    "Basic Board": "基础棋盘",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '*DISClAIMER* We love Jai': '*免责声明*我们爱Jai',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Enemy Skill: ": "敌方技能：",
    "Difficulty: ": "难度：",
    "Disadvantage: ": "劣势：",
    "Learning Rate: ": "学习率：",
    "Speed:": "速度：",
    "Toes:": "Toes:",
    "Skill: ": "技能：",
    "Unlocked at Tier ": "解锁于层 ",
    "LearningRate: ": "学习率：",
    "Basic: ": "基础: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Produces (.+) tics on tie$/, 'tie时产生 $1 tics'],
    [/^Produces (.+) toe per win$/, '每次获胜产生 $1 toe'],
    [/^Produces (.+) tics per win$/, '每次获胜产生 $1 tics'],
    [/^Produces (.+) tacs per tie$/, '每次平局产生 $1 tacs'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Cash Bonus: (.+) tics left$/, '现金奖励：还剩 $1 tics'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^([\d\.,]+) Toes$/, '$1 Toes'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);